const images = [
"Dr Oetker Veg Mayonnaise Smoky Peri Peri 1kg - Rs. 150.00, Mayonnaise.png",
"Dr Oetker Funfoods Italian Style Pasta And Pizza Sauce 1kg - Rs. 150.00, Sauce.png",
"Dr Oetker Funfoods Makhani Sauce For Pasta And Pizza 1kg - Rs. 150.00, Sauce.png",
"Dr Oetker Funfoods Salad Mayonnaise 1kg - Rs. 150.00, Mayonnaise.png",
"Dr Oetker Italian Style Pasta And Pizza Sauce No Onion No Garlic 1kg - Rs. 150.00, Sauce.png",
"GGF - Pav Bread - Rs. 50.00, Bread.png",
"GGF - Pizza Base - Rs. 25.00, Bread.png",
"Puliro American Bread Crumb - Rs. 200.00, Bakery.png",
"Puliro Bread Crumb - Rs. 200.00, Bakery.png",
"Puliro Panko Bread Crumb - Rs. 200.00, Bakery.png",
"Sriraja Panich Chilli Sauce 570gm - Rs. 100.00, Sauce.png",
"Woh Hup Black Pepper Sauce 340gm - Rs. 100.00, Sauce.png",
"Woh Hup Spicy Black Bean Sauce 340gm - Rs. 100.00, Sauce.png",
"Godrej Yummiez Crispy Veg Sticks 320gm - Rs. 350.00, Frozen Veg Snacks.png",
"Amul Mithai Mate - Rs. 150.00, Sweetened Condensed Milk.png",
"GGF - Burger Bun - Rs. 40.00, Bread.png",
"Finosta Penne Pasta - Rs. 150.00, Pasta.png",
"Frozen Basa Fillets - Rs. 2500.00, Frozen Fish.png",
"Golden Crown MSG - Rs. 100.00, Masale.png",
"Go Cheese Slices 750g + 50 g Free (50 pcs x 16 g) - Rs. 250.00, Cheese.png",
"Godrej Yummiez Chicken Burger 300gm - Rs. 350.00, Frozen Non-Veg Snacks.png",
"Godrej Yummiez Chicken Nuggets 500gm - Rs. 350.00, Frozen Non-Veg Snacks.png",
"Godrej Yummiez Chilli Garlic Potato Bites 420g - Rs. 350.00, Frozen Veg Snacks.png",
"Godrej Yummiez Veg Burger Patty 340gm - Rs. 350.00, Frozen Veg Snacks.png",
"GGF - Jumbo Sandwich Bread - Rs. 100.00, Bread.png",
"Lee Kum Kee Plum Sauce 260 g Bottle - Rs. 150, Sauce.png",
"Madras Ship Curry - Rs. 200.00, Masale.jpg",
"McCain CrispOns - Rs. 200.00, Frozen Veg Snacks.jpg",
"Nature Smith Smoked Paprika Powder 400g - Rs. 200.00, Maslae.jpg",
"NATURESMITH PAPRIKA POWDER 400g - Rs. 200.00, Maslae.jpg",
"Godrej Yummiez Cheesy Pizza Finger - Rs. 350.00, Frozen Veg Snacks.jpg",
"Nestle Maggi - Rs. 14.00, Noodles.jpg",
"Nestle KitKat - Rs. 200.00, Chocolate.jpg",
"Golden Crown Beans In Tomato Sauce 450gm - Rs. 100.00, Beans.jpg",
"Delta Toffee Caramel 1kg - Rs. 350.00, Spread.jpg",
"Finosta Fusilli Pasta - Rs. 150.00, Pasta.jpg",
"Finosta Spaghetti Pasta - Rs. 150.00, Pasta.jpg",
"Food Coast Mayo Lite 1 kg - Rs. 150.00, Mayonnaise.jpg",
"frozen-momoz - Rs. 150.00, Momos.jpg",
"Lotus Biscof Smooth Creamy Spread - Rs. 500, Spread.jpg",
"Lotus Biscofs Biscuits - Rs. 200.00, Biscuits.jpg",
"Namjai Tom Yum Soup Paste (Veg) 1 Kg - Rs. 200.00, Sauce.jpeg",
"Chef's Art Hyderabadi Biryani Powder Masala 500g - Rs. 250.00, Masale.jpeg",
"Go filler cheese 500g - Rs. 150.00, Cheese.jpeg",
];
